name: seq-base
channels:
  - conda-forge
  - bioconda
dependencies:
  - fastqc
  - fastp
  - samtools
  - bcftools
  - seqtk
  - multiqc
  - snakemake-minimal
  - gnuplot   # required by samtools' plot-bamstats
  - perl-uri  # provides URI::Escape, required by plot-bamstats
  - subread   # provides featureCounts
